name: bamboozler-env
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - samtools
  - bwa
  - wgsim
  - git
  - curl
  - openjdk=11
  - pip

  - pip:
      - .
      - git+https://github.com/ncsa/NEAT.git
      - git+https://github.com/bioinform/varsim.git
