name: bamboozler_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - samtools
  - bwa
  - wgsim
  - picard
  - exonerate
  - velvet
  - htslib
  - bcftools
  - refgenconf
  - gffutils
  - pybedtools
  - vcfpy
  - bamsurgeon
  - pip
  - pip:
      - .
      - git+https://github.com/ncsa/NEAT.git

